<?php
if (($kryptex_slider_sc = kryptex_get_theme_option('front_page_title_shortcode')) != '' && strpos($kryptex_slider_sc, '[')!==false && strpos($kryptex_slider_sc, ']')!==false) {

	?><div class="front_page_section front_page_section_title front_page_section_slider front_page_section_title_slider"><?php
		// Add anchor
		$kryptex_anchor_icon = kryptex_get_theme_option('front_page_title_anchor_icon');
		$kryptex_anchor_text = kryptex_get_theme_option('front_page_title_anchor_text');
		if ((!empty($kryptex_anchor_icon) || !empty($kryptex_anchor_text)) && shortcode_exists('trx_sc_anchor')) {
			echo do_shortcode('[trx_sc_anchor id="front_page_section_title"'
											. (!empty($kryptex_anchor_icon) ? ' icon="'.esc_attr($kryptex_anchor_icon).'"' : '')
											. (!empty($kryptex_anchor_text) ? ' title="'.esc_attr($kryptex_anchor_text).'"' : '')
											. ']');
		}
		// Show slider (or any other content, generated by shortcode)
		echo do_shortcode($kryptex_slider_sc);
	?></div><?php

} else {

	?><div class="front_page_section front_page_section_title<?php
				$kryptex_scheme = kryptex_get_theme_option('front_page_title_scheme');
				if (!kryptex_is_inherit($kryptex_scheme)) echo ' scheme_'.esc_attr($kryptex_scheme);
				echo ' front_page_section_paddings_'.esc_attr(kryptex_get_theme_option('front_page_title_paddings'));
			?>"<?php
			$kryptex_css = '';
			$kryptex_bg_image = kryptex_get_theme_option('front_page_title_bg_image');
			if (!empty($kryptex_bg_image))
				$kryptex_css .= 'background-image: url('.esc_url(kryptex_get_attachment_url($kryptex_bg_image)).');';
			if (!empty($kryptex_css))
				echo ' style="' . esc_attr($kryptex_css) . '"';
	?>><?php
		// Add anchor
		$kryptex_anchor_icon = kryptex_get_theme_option('front_page_title_anchor_icon');
		$kryptex_anchor_text = kryptex_get_theme_option('front_page_title_anchor_text');
		if ((!empty($kryptex_anchor_icon) || !empty($kryptex_anchor_text)) && shortcode_exists('trx_sc_anchor')) {
			echo do_shortcode('[trx_sc_anchor id="front_page_section_title"'
											. (!empty($kryptex_anchor_icon) ? ' icon="'.esc_attr($kryptex_anchor_icon).'"' : '')
											. (!empty($kryptex_anchor_text) ? ' title="'.esc_attr($kryptex_anchor_text).'"' : '')
											. ']');
		}
		?>
		<div class="front_page_section_inner front_page_section_title_inner<?php
			if (kryptex_get_theme_option('front_page_title_fullheight'))
				echo ' kryptex-full-height sc_layouts_flex sc_layouts_columns_middle';
			?>"<?php
				$kryptex_css = '';
				$kryptex_bg_mask = kryptex_get_theme_option('front_page_title_bg_mask');
				$kryptex_bg_color = kryptex_get_theme_option('front_page_title_bg_color');
				if (!empty($kryptex_bg_color) && $kryptex_bg_mask > 0)
					$kryptex_css .= 'background-color: '.esc_attr($kryptex_bg_mask==1
																		? $kryptex_bg_color
																		: kryptex_hex2rgba($kryptex_bg_color, $kryptex_bg_mask)
																	).';';
				if (!empty($kryptex_css))
					echo ' style="' . esc_attr($kryptex_css) . '"';
		?>>
			<div class="front_page_section_content_wrap front_page_section_title_content_wrap content_wrap">
				<?php
				// Caption
				$kryptex_caption = kryptex_get_theme_option('front_page_title_caption');
				if (!empty($kryptex_caption) || (current_user_can('edit_theme_options') && is_customize_preview())) {
					?><h1 class="front_page_section_caption front_page_section_title_caption front_page_block_<?php echo !empty($kryptex_caption) ? 'filled' : 'empty'; ?>"><?php echo wp_kses_post($kryptex_caption); ?></h1><?php
				}
			
				// Description (text)
				$kryptex_description = kryptex_get_theme_option('front_page_title_description');
				if (!empty($kryptex_description) || (current_user_can('edit_theme_options') && is_customize_preview())) {
					?><div class="front_page_section_description front_page_section_title_description front_page_block_<?php echo !empty($kryptex_description) ? 'filled' : 'empty'; ?>"><?php echo wp_kses_post(wpautop($kryptex_description)); ?></div><?php
				}
				
				// Buttons
				if (kryptex_get_theme_option('front_page_title_button1_link')!='' || kryptex_get_theme_option('front_page_title_button2_link')!='') {
					?><div class="front_page_section_buttons front_page_section_title_buttons"><?php
						kryptex_show_layout(kryptex_customizer_partial_refresh_front_page_title_button1_link());
						kryptex_show_layout(kryptex_customizer_partial_refresh_front_page_title_button2_link());
					?></div><?php
				}
				?>
			</div>
		</div>
	</div>
	<?php
}